---

- name: Check exist ports tree
  stat:
    path: /usr/ports
  register: ports

- block:
  - name: Create var/db/portsnap
    file:
      path: /var/db/portsnap
      state: directory      

  - name: Copy portsnap script
    template: 
      src: portsnap-local.j2
      dest: /root/portsnap-local
      mode: 0555

  - name: Download fresh freebsd ports
    command: |
      sh /root/portsnap-local

  - name: Extract fresh ports
    command: |
      portsnap extract

  when: ports.stat.exists == false

# check stolon ports
- include: "ports.yml port={{ outer_port }}"
  loop:
    # - stolon
    - dns-ui
  loop_control:
    loop_var: outer_port
